--- 
steps: 
  - 
    args: 
      - cluster-info
    env: 
      - CLOUDSDK_COMPUTE_ZONE=us-west1
      - CLOUDSDK_CONTAINER_CLUSTER=opus-gke-we1-np-prep
      - KUBECONFIG=/workspace/.kube/config
    name: gcr.io/cloud-builders/kubectl
#  - 
#    args: 
#      - create
#      - namespace
#      - spinnaker
#    env: 
#      - CLOUDSDK_COMPUTE_ZONE=us-west1
#      - CLOUDSDK_CONTAINER_CLUSTER=opus-gke-we1-np-prep
 #   name: gcr.io/cloud-builders/kubectl
  - 
    args: 
      - install
      - spinnaker
      - "--namespace"
      - spinnaker2
      - opsmx/spinnaker
    env: 
      - KUBECONFIG=/workspace/.kube/config
      - HELM_REPO_NAME=opsmx
      - "HELM_REPO_URL=https://helmcharts.opsmx.com/"
      - TILLERLESS=false
      - TILLER_NAMESPACE=test
    name: gcr.io/$PROJECT_ID/helm
