steps:

# fetch GKE cluster credentials to be used for helm step
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=example-private-cluster'
  - 'KUBECONFIG=/workspace/.kube/config'
  args: ['cluster-info']

 
#- name: 'gcr.io/cloud-builders/kubectl'
 # args: ['create','namespace','test-spinnaker']
  #env:
  #- 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
  #- 'CLOUDSDK_CONTAINER_CLUSTER=example-private-cluster'

   
# run helm command to install/upgrade spinnaker
# optionally you can set to add any other Helm chart repository
# to use charts from
- name: 'gcr.io/$PROJECT_ID/helm'
 # args: ['upgrade', '--install', 'spinnaker', '--namespace', 'test-spinnaker', 'opsmx/spinnaker']
  args: ['install', 'spinnaker2', '--namespace', 'test-spinnaker', 'opsmx/spinnaker']
  env:
  - 'KUBECONFIG=/workspace/.kube/config'
  - 'HELM_REPO_NAME=opsmx'
  - 'HELM_REPO_URL=https://helmcharts.opsmx.com/'
  - 'TILLERLESS=false'
  - 'TILLER_NAMESPACE=test'

